debug = true

[config]
  num_workers=2

[sampling]
  seed=0
  distribution='uniform'
  lower_bound=-2
  upper_bound=2
  number_of_samples_per_iteration=1


[task]
  name = 'iris'

[storage]
  data_base_path='data'
  commit_population_freq=10
  log_filename='execution.log'
  # if the confusion_matrices are required during inspection, they can still be calculated
  include_prediction_records=false

[population]
  num_generations = 20
  size = 64

[selection]
  # 'nsga_rank' and 'tournament' are mutually exclusie
  types = ['elite', 'nsga_rank']
  elite_size = 10
  tournament_size = 5

[mutation]
  [mutation.new_edge]
    propability = 0.25
    strategy = 'layer_agnostic'
  [mutation.new_node]
    propability = 0.25
  [mutation.reenable_edge]
    propability = 0.25
  [mutation.change_activation]
    propability = 0.25
