

[config]
  num_workers=1
  debug=true
  backend='numpy'

[postopt]
  run_postopt=true
  compile_report=true
  num_weights=100
  num_samples=1000

[sampling]
  seed=0
  # if not false, set seed after initial population was generated
  # used to determine how much influence the initial pop has
  post_init_seed=false
  distribution='uniform'
  lower_bound=-2
  upper_bound=2
  mean=0
  sigma=1
  num_weights_per_iteration=1
  num_samples_per_iteration=-1 # all
  hof_evaluation_iterations = 20

[task]
  name = 'iris'
  sample_order_seed = 0
  test_portion = 0.2
  sample_length = 10
  num_categories = 8

[storage]
  data_base_path='data'
  log_filename='execution.log'
  commit_elite_freq=-1 # never
  commit_metrics_freq=10

[population]
  num_generations = 20
  size = 64
  initial_enabled_edge_prob = 0.05
  initial_genes='full'
  initial_func='random'
  hof_size=10
  enable_edge_signs=false
  enabled_activation_funcs='all'

[selection]
  use_tournaments = true
  elite_ratio = 0.1
  culling_ratio = 0.2 # Don't use the worst 20% of the population for further variations
  tournament_size = 5
  objectives = ['-log_loss.min', '-log_loss.mean', '-n_hidden']
  recorded_metrics = ['accuracy', 'kappa', 'log_loss']
  hof_metric = 'accuracy.mean'



[mutation]
  [mutation.new_edge]
    probability = 0.20
    strategy = 'layer_agnostic'
  [mutation.new_node]
    probability = 0.25
  [mutation.reenable_edge]
    probability = 0.05
  [mutation.change_activation]
    probability = 0.5

  # will be ignored if edges signs are disabled
  [mutation.change_edge_sign]
    probability = 0.2

  # will be ignored if task does not require recurrence
  [mutation.new_recurrent_edge]
    probability = 0.2
    strategy='any' # other option: loops_only ('any' creates loops as well)
