debug = true

[config]
  num_workers=1
  run_post_opt=true

[sampling]
  seed=0
  distribution='uniform'
  lower_bound=-2
  upper_bound=2
  num_weight_samples_per_iteration=1
  num_training_samples_per_iteration=-1 # all
  hof_evaluation_iterations = 20

[task]
  name = 'iris'

[storage]
  data_base_path='data'
  commit_population_freq=10
  log_filename='execution.log'
  # if the confusion_matrices are required during inspection, they can still be calculated
  include_prediction_records=false

[population]
  num_generations = 20
  size = 64
  initial_enabled_edge_probability = 0.05
  initial_with_edges=true
  hof_size=10

[selection]
  use_tournaments = true
  elite_ratio = 0.1
  culling_ratio = 0.2 # Don't use the worst 20% of the population for further variations
  tournament_size = 5



[mutation]
  [mutation.new_edge]
    propability = 0.20
    strategy = 'layer_agnostic'
  [mutation.new_node]
    propability = 0.25
  [mutation.reenable_edge]
    propability = 0.05
  [mutation.change_activation]
    propability = 0.5
